image:
  repository: repository_url_to_replace
  tag: '0.0.1'
  pullPolicy: 'Always'

## edit those environment variables
## ----------------------
nonSensitiveEnvs:
  CTP_PROJECT_KEY: client_project_to_replace
  CTP_API_URL: 'https://api.europe-west1.gcp.commercetools.com'
  CTP_AUTH_URL: 'https://auth.europe-west1.gcp.commercetools.com'

sensitiveEnvs:
  CTP_CLIENT_ID: client_id_to_replace
  CTP_CLIENT_SECRET: client_secret_to_replace
## ----------------------

# When the pod is scheduled, the container is guaranteed the amount of
# resources requested 512MB RAM. As we don't know how much memory the jobs will
# need, we don't set the limit
resources:
  requests:
    memory: '1024Mi'

# specifies how to treat concurrent executions of a job created by this cron job
concurrency: Forbid

# Avoid scheduling with this hack: as there is no day like 31 Feb :)
schedule: '*/5 * * * *'
