# This workflow will build docker images and publish to docker hub
# For more information see: https://github.com/marketplace/actions/build-and-push-docker-images

name: CD

on: [push]
#on:
#  push:
#    tags:
#      - 'v*.*.*'

jobs:
  build:
    concurrency: build
    runs-on: ubuntu-latest
    env:
      CTP_PROJECT_KEY: ctp-subscriptions-ci-it
      CTP_CLIENT_ID: ${{ secrets.CTP_CLIENT_ID }}
      CTP_CLIENT_SECRET: ${{ secrets.CTP_CLIENT_SECRET }}
      AWS_ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}
      AWS_REGION_CODE: ${{ secrets.AWS_REGION_CODE }}
      AWS_ECR_PATH: ${{ secrets.AWS_ECR_PATH }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: AWS_REGION_CODE

      - name: Build docker and deploy to ECR
        run: deployment-examples/aws/k8s/deploy_to_eks.sh
